# Generated by Django 4.0.4 on 2022-04-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imageurl',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
